name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build-and-push-image-to-heroku:
    name: Build image and push to Heroku
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_PASSWORD }}
      run: heroku container:login
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_PASSWORD }}
      run: heroku container:push -a ${{ secrets.HEROKU_APPLICATION_NAME }} web 
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_PASSWORD }}
      run: heroku container:release -a ${{ secrets.HEROKU_APPLICATION_NAME }} web
